name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'main.py'
        requirements: 'requirements.txt'
        python_ver: '3.9'
        options: |
          --onefile,
          --windowed,
          --name "EXR Matte Embed",
          --icon "${{ matrix.os == 'windows-latest' && 'images/icon.ico' || 'images/icon.icns' }}"
        upload_exe_with_name: 'EXR-Matte-Embed-${{ matrix.os }}'

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startswith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.pyinstaller-build.outputs.executable_path }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
